### PR TITLE
Update chatgpt_automation.py

### PR DESCRIPTION
**Pull request by Cfomodz**

### CODE REVIEW

**Comment by fillwithjoy1** [comment]
literally a massive error by OP

**Comment by Cfomodz** [comment]
> literally a massive error by OP

When I ran it and it didn’t work I just asked chatGPT what the problem was and it told me.

^ this is a joke, but the PR really should be merged 😛

**Comment by fillwithjoy1** [comment]
Yeah I know 😂, is this repo a joke? I might just start making my own repo to compete with this

**Comment by Erol444** [comment]
Self promo: https://github.com/Erol444/gpt4-openai-api#gpt4-openai-unofficial-api does the same thing as this repo, but it actually works:)

**Comment by fillwithjoy1** [comment]
LMFAO, they are deleting comments that slander them XD

**Comment by Cfomodz** [comment]
What the heck?! I fixed your code and you don't just delete the comments discussing open source work moving forward but also close the branch unmerged? Lol! Did you also then just take my working code and replace the broken code but weren't willing to accept my changes so you redid my work yourself?

**Comment by Cfomodz** [comment]
> LMFAO, they are deleting comments that slander them XD

Nice ;)

**Comment by fillwithjoy1** [comment]
> > LMFAO, they are deleting comments that slander them XD
> 
> Nice ;)

@querybila is the kind of guy who will copy a friends joke and then say he made it up all by himself

**Pull request closed without merging**
